import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from "./lib/ThemeProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import React, { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ThemeProvider>
  );
}
